<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>

		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PackageId>NBTerminal</PackageId>
		<Version>0.1.0</Version>
		<Title>NBTerminal</Title>
		<Authors>postmium</Authors>

		<Description>A lightweight, event-driven .NET terminal library with non-blocking input, independent rendering, and page management.</Description>

		<PackageTags>terminal;console;non-blocking;event-driven;rendering</PackageTags>

		<PackageLicenseExpression>MIT</PackageLicenseExpression>

		<RepositoryUrl>https://github.com/postmium/NBTerminal</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<PackageReadmeFile>README.md</PackageReadmeFile>

	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>